[TO] Added resource mapping use case
stakater/stakater-docs pull request #53
Opened 2022-10-14 07:39 UTC by hussnain612

2022-10-14 07:42 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-53-b4d39e28`

2022-10-14 07:52 UTC, MahnoorAsghar commented on docs/content/sre/tenant-operator/customresources.md
> +* They either contains one or more Kubernetes manifests, reference to some secrets and configMaps or alternatively a Helm chart.
They either **contain** one or more Kubernetes manifests, a reference to a secret or configMap, or a Helm chart. -- grammar + reads better

2022-10-14 07:54 UTC, MahnoorAsghar commented on docs/content/sre/tenant-operator/usecases/template.md
> +**Note:** Resource mapping could only be used via TGI to map resources within tenant namespaces or to some other tenant's namespace.
Resource mapping **can** only be used via TGI to map resources within tenant namespaces, or to some other tenant's namespace.

2022-10-14 07:59 UTC, MahnoorAsghar commented on docs/content/sre/tenant-operator/customresources.md
> +  <p>The templates can be specified with secrets and configMaps that can be mapped from one tenant's namespace to some other tenant's namespace or within a tenant's namespace.</p>
A template can be used to map secrets and configMaps from one tenant's namespace to another tenant's namespace, or within a tenant's namespace.

2022-10-14 08:00 UTC, MahnoorAsghar commented on docs/content/sre/tenant-operator/customresources.md
> +  <p>The templates can be specified with secrets and configMaps that can be mapped from one tenant's namespace to some other tenant's namespace or within a tenant's namespace.</p>
The rest of the points are using a more active voice, so this point should too. It also sounds clearer :)

2022-10-18 04:40 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-53-c412114e`

2022-10-18 05:40 UTC, abdulhaseeb2 requested changes

2022-10-18 05:40 UTC, abdulhaseeb2 commented on docs/content/sre/tenant-operator/customresources.md
> +Templates are used to initialize Namespaces, share common resources across namespaces, and map secrets and configMaps from one namespace to other namespaces.
'and map secret/configMaps from one namespace to other namespaces.'
^ Update it to this if this makes more sense.

2022-10-18 05:40 UTC, abdulhaseeb2 commented on docs/content/sre/tenant-operator/customresources.md
> +* They either contain one or more Kubernetes manifests, a reference to secrets or configMaps, or a Helm chart.
`a reference to secrets/configMaps, or a Helm chart.`
same here

2022-10-18 05:47 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-53-c5a8dc2e`

2022-10-18 11:46 UTC, stakater-user commented
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-53-1eed4068`

2022-10-18 12:13 UTC, stakater-user commented
@LilShah Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-53-2f886729`

2022-10-18 12:20 UTC, abdulhaseeb2 approved these changes

2022-10-18 12:22 UTC, merged

2022-10-18 12:25 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.33`