[MTO] Updated installation process for MTO
stakater/stakater-docs pull request #55
Opened 2022-10-17 18:01 UTC by hussnain612

Updated the installation process of MTO from OperatorHub

2022-10-17 18:03 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-55-91f8c815`

2022-10-18 04:55 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-55-0b70badd`

2022-10-18 05:06 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-55-7fff6d02`

2022-10-18 06:24 UTC, abdulhaseeb2 requested changes

2022-10-18 06:24 UTC, abdulhaseeb2 commented on docs/content/sre/tenant-operator/installation.md
>  --set resources.limits.cpu=600m \
Increase CPU to 1000m

2022-10-18 06:24 UTC, abdulhaseeb2 commented on docs/content/sre/tenant-operator/installation.md
>          cpu: 600m
Increase CPU to 1000m

2022-10-18 06:57 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-55-db46eb75`

2022-10-18 12:29 UTC, MuneebAijaz approved these changes

2022-10-18 12:30 UTC, abdulhaseeb2 approved these changes

2022-10-18 12:30 UTC, merged

2022-10-18 12:30 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-55-fa8fd11d`

2022-10-18 12:33 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.34`