SAAP onboarding
stakater/stakater-docs pull request #73
Opened 2022-11-09 21:34 UTC by karl-johan-grahn

Onboarding process

2022-11-09 21:37 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-73-951b6b22`

2022-11-10 09:30 UTC, AsfaMumtaz requested changes

2022-11-10 09:30 UTC, AsfaMumtaz commented on docs/content/onboarding/onboarding.md
> +
We also need to create a chart after this step

2022-11-10 16:06 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-73-2eeb0ac6`

2022-11-10 16:07 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-73-b62637d5`

2022-11-11 06:25 UTC, mustafaStakater commented on docs/content/onboarding/onboarding.md
> +- Select the first application
1. Setup infra & apps gitops repository for deploying application and dependent configurations.

2. Setup the tenant operator configurations and decided on the number of environments if required.

3. Select the application or group of applications that work together and divide them into microservices  and containerize them.

4. Deploy the application onto the cluster using Kubernetes Resources. List out secret required, dependent services, databases, storage requirements and implement them accordingly.

5. Deploy Kubernetes Resources using Stakater Developed Helm Chart on the environment your choice (prod,stage,test,dev) in apps-gitops-config.
Available at  : https://github.com/stakater/application

6. Implement CI pipeline for the application if required. Deploy tekton CI pipeline using Stakater Tekton Chart.

7. Implement monitoring, logging, validation/testing frameworks or any additional tools for the application.

8. Repeat the steps for other applications 2 to 7 for other application(s).

2022-11-11 09:32 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-73-313af89e`

2022-11-11 12:05 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-73-ce7ee60e`

2022-11-11 12:05 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-73-2c38b863`

2022-11-13 19:31 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-73-80e8ffc8`

2022-11-15 07:07 UTC, AsfaMumtaz approved these changes

2022-11-15 07:07 UTC, merged

2022-11-15 07:09 UTC, stakater-user commented
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:v0.0.51`