Adds total machine cost info
stakater/stakater-docs pull request #84
Opened 2022-11-22 06:51 UTC by KhizerJaan

2022-11-22 06:53 UTC, stakater-user commented
@KhizerJaan Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-84-1c9ea2cf`

2022-11-22 07:38 UTC, usamaahmadkhan approved these changes

2022-11-22 07:40 UTC, usamaahmadkhan requested changes

2022-11-22 07:40 UTC, usamaahmadkhan commented on docs/content/sre/machinepools/machinepools.md
> +|  Binero | 8 | 48 GB | 2080 SEK  |
we use 8x32 GB not 8x64. Plz change this for both

2022-11-22 09:52 UTC, stakater-user commented
@KhizerJaan Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-84-bb9b49b8`

2022-11-25 12:32 UTC, karl-johan-grahn commented
redundant

2022-11-25 12:32 UTC, closed without merging