Added workflows and deployment
stakater/stakater-docs pull request #9
Opened 2022-07-28 11:32 UTC by hussnain612

2022-07-28 12:04 UTC, abdulhaseeb2 requested changes

2022-07-28 12:04 UTC, abdulhaseeb2 commented on .github/workflows/pull_request.yaml
> +      - 'master'
* main

2022-07-28 12:04 UTC, abdulhaseeb2 commented on .github/workflows/push.yaml
> +      - 'master'
* main

2022-07-28 12:12 UTC, MuneebAijaz commented on deployments/kubernetes/templates/chart/values.yaml.tmpl
> +    name: "stakaterclouddocs-2.0"
do k8s object support this dot format? also you can mention it as stakakterclouddocs2 or stakaterclouddocs-v2.

2022-07-28 12:13 UTC, MuneebAijaz commented on deployments/kubernetes/templates/chart/Chart.yaml.tmpl
> +- name: Waleed Malik
Update name here as well

2022-07-28 12:13 UTC, MuneebAijaz commented on deployments/kubernetes/chart/stakaterclouddocs/values.yaml
> +stakaterclouddocs-2.0:
pls verify if chart names support dots format

2022-07-28 12:36 UTC, stakater-user commented
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/stakater-cloud-docs-2.0/commit/519e18da42bffed3326de89cb597d5561d5b2712/checks) has Failed!

2022-07-28 12:39 UTC, hussnain612 commented on .github/workflows/pull_request.yaml
> +      - 'master'
Updated

2022-07-28 12:40 UTC, hussnain612 commented on .github/workflows/push.yaml
> +      - 'master'
Updated

2022-07-28 12:40 UTC, hussnain612 commented on deployments/kubernetes/templates/chart/values.yaml.tmpl
> +    name: "stakaterclouddocs-2.0"
Updated with v2

2022-07-28 12:40 UTC, hussnain612 commented on deployments/kubernetes/templates/chart/Chart.yaml.tmpl
> +- name: Waleed Malik
Updated

2022-07-28 12:40 UTC, hussnain612 commented on deployments/kubernetes/chart/stakaterclouddocs/values.yaml
> +stakaterclouddocs-2.0:
Updated

2022-07-29 10:19 UTC, stakater-user commented
@hussnain612 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/stakater-cloud-docs-2.0/commit/0ef1f9a69e854065cf35929294191c3e792a8c43/checks) has Failed!

2022-07-29 10:30 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakater-cloud-docs-2.0:SNAPSHOT-PR-9-1c2b48e9`

2022-07-29 10:35 UTC, MuneebAijaz approved these changes

2022-07-29 10:48 UTC, merged

2022-07-29 10:50 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakater-cloud-docs-2.0:v0.0.1`